CasinoBae.UI=CasinoBae.UI or {}
local frame
local function bg(f,c,b) f:SetBackdrop({bgFile="Interface/Buttons/WHITE8X8",edgeFile="Interface/Buttons/WHITE8X8",edgeSize=1}); f:SetBackdropColor(unpack(c)); f:SetBackdropBorderColor(unpack(b or c)) end
local function txt(p,t,s,c) local x=p:CreateFontString(nil,"OVERLAY","GameFontNormal"); x:SetFont(STANDARD_TEXT_FONT,s or 10,""); x:SetTextColor(unpack(c or {1,1,1,1})); x:SetText(t or ""); return x end
local function btn(p,t,x,y,w,fn,on) local b=CreateFrame("Button",nil,p,"BackdropTemplate"); b:SetSize(w or 90,31); b:SetPoint("TOPLEFT",x,y); bg(b,on and {0.75,0.08,0.28,1} or {0.09,0.075,0.12,1},on and {1,0.35,0.65,1} or {0.28,0.24,0.32,1}); b.t=txt(b,t,9); b.t:SetPoint("CENTER"); b:SetScript("OnClick",fn); return b end
local P={1,0.24,0.60,1}; local G={0.43,0.91,0.63,1}; local Y={1,0.78,0.34,1}; local M={0.48,0.45,0.52,1}
local function ensure() if frame then return frame end
frame=CreateFrame("Frame","CasinoBaeStatusFrame",UIParent,"BackdropTemplate"); frame:SetSize(760,512); frame:SetPoint("CENTER",0,-20); frame:Hide(); frame:SetMovable(true); frame:EnableMouse(true); frame:RegisterForDrag("LeftButton"); frame:SetScript("OnDragStart",frame.StartMoving); frame:SetScript("OnDragStop",frame.StopMovingOrSizing); bg(frame,{0.018,0.014,0.024,0.99},{0.75,0.12,0.40,1})
frame.top=CreateFrame("Frame",nil,frame,"BackdropTemplate"); frame.top:SetPoint("TOPLEFT",1,-1); frame.top:SetPoint("TOPRIGHT",-1,-1); frame.top:SetHeight(66); bg(frame.top,{0.065,0.025,0.055,1},{0.22,0.16,0.24,1})
frame.a=txt(frame.top,"CASINO",20); frame.a:SetPoint("TOPLEFT",20,-12); frame.b=txt(frame.top,"BAE",20,P); frame.b:SetPoint("LEFT",frame.a,"RIGHT",5,0); frame.sub=txt(frame.top,"HOST LOUNGE  /  LIVE GAME CONTROL",8,M); frame.sub:SetPoint("TOPLEFT",21,-39); frame.status=txt(frame.top,"● READY",10,M); frame.status:SetPoint("TOPRIGHT",-20,-25)
frame.phase=txt(frame,"LOBBY OPEN",13); frame.phase:SetPoint("TOPLEFT",22,-84); frame.detail=txt(frame,"Ready to host.",9,M); frame.detail:SetPoint("TOPLEFT",22,-105); frame.detail:SetWidth(710)
frame.hero=CreateFrame("Frame",nil,frame,"BackdropTemplate"); frame.hero:SetPoint("TOPLEFT",20,-122); frame.hero:SetSize(720,112); bg(frame.hero,{0.045,0.032,0.055,1},{0.22,0.16,0.24,1})
frame.heroTitle=txt(frame.hero,"HIGH ROLL",9,P); frame.heroTitle:SetPoint("TOPLEFT",18,-16); frame.heroRound=txt(frame.hero,"ROUND 00",8,M); frame.heroRound:SetPoint("TOPRIGHT",-18,-16); frame.heroValue=txt(frame.hero,"WAITING",30); frame.heroValue:SetPoint("TOPLEFT",18,-42); frame.heroHint=txt(frame.hero,"Le vrai /rand reste la source de vérité.",8,M); frame.heroHint:SetPoint("BOTTOMLEFT",18,13); frame.heroBadge=txt(frame.hero,"READY",9,G); frame.heroBadge:SetPoint("BOTTOMRIGHT",-18,13)
frame.playersBox=CreateFrame("Frame",nil,frame,"BackdropTemplate"); frame.playersBox:SetPoint("TOPLEFT",20,-246); frame.playersBox:SetSize(450,142); bg(frame.playersBox,{0.035,0.028,0.045,1},{0.20,0.16,0.23,1}); frame.playersTitle=txt(frame.playersBox,"PLAYERS",8,M); frame.playersTitle:SetPoint("TOPLEFT",15,-14); frame.rows={}
for i=1,6 do local r=CreateFrame("Frame",nil,frame.playersBox,"BackdropTemplate"); local c=(i-1)%2; local q=math.floor((i-1)/2); r:SetSize(205,30); r:SetPoint("TOPLEFT",13+c*218,-31-q*34); bg(r,{0.055,0.045,0.068,1},{0.14,0.12,0.17,1}); r.n=txt(r,"—",9); r.n:SetPoint("LEFT",9,0); r.v=txt(r,"—",16,M); r.v:SetPoint("RIGHT",-9,0); frame.rows[i]=r end
frame.feed=CreateFrame("Frame",nil,frame,"BackdropTemplate"); frame.feed:SetPoint("TOPLEFT",484,-246); frame.feed:SetSize(256,142); bg(frame.feed,{0.035,0.028,0.045,1},{0.20,0.16,0.23,1}); frame.feedTitle=txt(frame.feed,"HOST FEED",8,M); frame.feedTitle:SetPoint("TOPLEFT",15,-14); frame.feedText=txt(frame.feed,"Ready to host.",9,M); frame.feedText:SetPoint("TOPLEFT",15,-36); frame.feedText:SetWidth(225)
btn(frame,"OPEN LOBBY",20,-420,105,function() CasinoBae:CreateLobby() end,true); btn(frame,"START ROUND",133,-420,105,function() local ok,e=CasinoBae.Game:StartRand(); if not ok then CasinoBae:Announce(e) end end,true); btn(frame,"RULES",246,-420,82,function() CasinoBae:Announce("RAND 1-100 — chacun lance /rand — plus haut gagne — égalité = relance.") end); btn(frame,"YELL",336,-420,82,function() CasinoBae:Yell("CASINOBAE — LA MANCHE COMMENCE !") end); btn(frame,"EMOTE",426,-420,82,function() CasinoBae:Emote("CHEER") end); btn(frame,"HIDE",516,-420,82,function() frame:Hide() end); btn(frame,"STATUS",606,-420,82,function() CasinoBae.UI:PrintStatus() end)
btn(frame,"START FULL CASINO DEMO",20,-455,640,function() if CasinoBae.Style then CasinoBae:Announce("DEMO Casinobabe : que le spectacle commence."); CasinoBae.Style.Demo() else CasinoBae:Announce("Module Style indisponible.") end end,true)
frame.hint=txt(frame,"/cb help  •  drag the top bar  •  protected actions never fake success",8,{0.36,0.33,0.40,1}); frame.hint:SetPoint("BOTTOMLEFT",20,9); return frame end
function CasinoBae.UI:Show() ensure():Show(); self:Refresh() end; function CasinoBae.UI:Hide() ensure():Hide() end
function CasinoBae.UI:Refresh() local f=ensure(); local s=tostring(CasinoBae.STATE); local d=CasinoBae.stateDetail or {}; f.phase:SetText(s=="GAME_WAITING_FOR_ROLLS" and "HIGH ROLL  •  LIVE" or s=="ROUND_COMPLETE" and "ROUND COMPLETE" or s=="TIE" and "TIE  •  REROLL" or s=="ACTION_REQUIRED" and "ACTION REQUIRED" or "LOBBY OPEN"); f.detail:SetText(d.message or d.action or (d.winner and ("Winner: "..d.winner.."  •  "..tostring(d.value))) or "Ready to host."); f.heroRound:SetText("ROUND "..string.format("%02d",CasinoBae.lobby.round or 0)); f.heroValue:SetText(d.winner and (d.winner.."  •  "..tostring(d.value)) or (s=="GAME_WAITING_FOR_ROLLS" and "ROLL NOW" or s=="TIE" and "TIE" or "WAITING")); f.heroBadge:SetText(s=="GAME_WAITING_FOR_ROLLS" and "● LIVE" or s=="ACTION_REQUIRED" and "ACTION" or s=="ROUND_COMPLETE" and "WINNER" or "READY"); f.heroBadge:SetTextColor(unpack(s=="GAME_WAITING_FOR_ROLLS" and G or s=="ACTION_REQUIRED" and Y or s=="ROUND_COMPLETE" and P or M));
local names={}; for n in pairs(CasinoBae.lobby.players or {}) do names[#names+1]=n end; table.sort(names); local rolls=CasinoBae.rolls or {}; for i,r in ipairs(f.rows) do local n=names[i]; if n then r:Show(); r.n:SetText(n); local v=rolls[n]; r.v:SetText(v and tostring(v) or "—"); r.v:SetTextColor(unpack(v and P or M)) else r:Hide() end end; f.playersTitle:SetText("PLAYERS  •  "..#names); f.feedText:SetText(s=="GAME_WAITING_FOR_ROLLS" and "Round live. Waiting for real /rand events." or s=="ACTION_REQUIRED" and "Human action required. CasinoBae resumes after real WoW confirmation." or d.winner and ("Winner confirmed: "..d.winner.." ("..tostring(d.value)..").") or "Ready to host.") end
function CasinoBae.UI:SetActionRequired(message,action) CasinoBae:RequireAction(message,action or "MANUAL"); self:Show() end
function CasinoBae.UI:PrintStatus() self:Refresh(); self:Show(); print("|cffff4f9aCasinoBae|r state: "..tostring(CasinoBae.STATE)); local n=0 for _ in pairs(CasinoBae.lobby.players or {}) do n=n+1 end; print(" players: "..n.." round: "..tostring(CasinoBae.lobby.round or 0)) end